<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Reglas de Asociación y Modelos de Clasificación</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="reporte_files/libs/clipboard/clipboard.min.js"></script>
<script src="reporte_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="reporte_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="reporte_files/libs/quarto-html/popper.min.js"></script>
<script src="reporte_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="reporte_files/libs/quarto-html/anchor.min.js"></script>
<link href="reporte_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="reporte_files/libs/quarto-html/quarto-syntax-highlighting-a06763021a52c43c40a351ac8b799b8f.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="reporte_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="reporte_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="reporte_files/libs/bootstrap/bootstrap-7927b542fa1d84950307462b573002e1.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Contenido</h2>
   
  <ul>
  <li><a href="#introducción" id="toc-introducción" class="nav-link active" data-scroll-target="#introducción"><span class="header-section-number">1</span> Introducción</a>
  <ul class="collapse">
  <li><a href="#contexto-del-problema" id="toc-contexto-del-problema" class="nav-link" data-scroll-target="#contexto-del-problema"><span class="header-section-number">1.1</span> Contexto del problema</a></li>
  <li><a href="#objetivos" id="toc-objetivos" class="nav-link" data-scroll-target="#objetivos"><span class="header-section-number">1.2</span> Objetivos</a></li>
  <li><a href="#descripción-del-dataset" id="toc-descripción-del-dataset" class="nav-link" data-scroll-target="#descripción-del-dataset"><span class="header-section-number">1.3</span> Descripción del dataset</a></li>
  </ul></li>
  <li><a href="#algoritmo-apriori" id="toc-algoritmo-apriori" class="nav-link" data-scroll-target="#algoritmo-apriori"><span class="header-section-number">2</span> Algoritmo Apriori</a>
  <ul class="collapse">
  <li><a href="#descripción" id="toc-descripción" class="nav-link" data-scroll-target="#descripción"><span class="header-section-number">2.1</span> Descripción</a></li>
  <li><a href="#python" id="toc-python" class="nav-link" data-scroll-target="#python"><span class="header-section-number">2.2</span> Python</a></li>
  </ul></li>
  <li><a href="#descubrimiento-de-patrones-reglas-de-asociación" id="toc-descubrimiento-de-patrones-reglas-de-asociación" class="nav-link" data-scroll-target="#descubrimiento-de-patrones-reglas-de-asociación"><span class="header-section-number">3</span> Descubrimiento de patrones: Reglas de Asociación</a>
  <ul class="collapse">
  <li><a href="#conocimiento-de-la-problemática" id="toc-conocimiento-de-la-problemática" class="nav-link" data-scroll-target="#conocimiento-de-la-problemática"><span class="header-section-number">3.1</span> Conocimiento de la problemática</a></li>
  <li><a href="#analitica-y-preparacion-de-datos" id="toc-analitica-y-preparacion-de-datos" class="nav-link" data-scroll-target="#analitica-y-preparacion-de-datos"><span class="header-section-number">3.2</span> Analitica y preparacion de datos</a>
  <ul class="collapse">
  <li><a href="#preparación-de-datos" id="toc-preparación-de-datos" class="nav-link" data-scroll-target="#preparación-de-datos"><span class="header-section-number">3.2.1</span> Preparación de datos</a></li>
  <li><a href="#tratamiento-de-datos-faltantes-mcar-vs-mar" id="toc-tratamiento-de-datos-faltantes-mcar-vs-mar" class="nav-link" data-scroll-target="#tratamiento-de-datos-faltantes-mcar-vs-mar"><span class="header-section-number">3.2.2</span> Tratamiento de datos faltantes (MCAR vs MAR)</a></li>
  <li><a href="#manejo-de-datos-confidenciales" id="toc-manejo-de-datos-confidenciales" class="nav-link" data-scroll-target="#manejo-de-datos-confidenciales"><span class="header-section-number">3.2.3</span> Manejo de datos confidenciales</a></li>
  <li><a href="#discretizacion-de-variables-continuas" id="toc-discretizacion-de-variables-continuas" class="nav-link" data-scroll-target="#discretizacion-de-variables-continuas"><span class="header-section-number">3.2.4</span> Discretizacion de variables continuas</a></li>
  </ul></li>
  <li><a href="#construccion-y-evaluacion-del-modelo-de-reglas" id="toc-construccion-y-evaluacion-del-modelo-de-reglas" class="nav-link" data-scroll-target="#construccion-y-evaluacion-del-modelo-de-reglas"><span class="header-section-number">3.3</span> Construccion y evaluacion del modelo de reglas</a></li>
  <li><a href="#refinamiento-y-ajuste" id="toc-refinamiento-y-ajuste" class="nav-link" data-scroll-target="#refinamiento-y-ajuste"><span class="header-section-number">3.4</span> Refinamiento y ajuste</a>
  <ul class="collapse">
  <li><a href="#eliminiacion-de-redundancia" id="toc-eliminiacion-de-redundancia" class="nav-link" data-scroll-target="#eliminiacion-de-redundancia"><span class="header-section-number">3.4.1</span> Eliminiacion de redundancia</a></li>
  <li><a href="#restricciones-en-reglas" id="toc-restricciones-en-reglas" class="nav-link" data-scroll-target="#restricciones-en-reglas"><span class="header-section-number">3.4.2</span> Restricciones en reglas</a></li>
  <li><a href="#reglas-maximas" id="toc-reglas-maximas" class="nav-link" data-scroll-target="#reglas-maximas"><span class="header-section-number">3.4.3</span> Reglas maximas</a></li>
  <li><a href="#reglas-en-transacciones" id="toc-reglas-en-transacciones" class="nav-link" data-scroll-target="#reglas-en-transacciones"><span class="header-section-number">3.4.4</span> Reglas en transacciones</a></li>
  </ul></li>
  <li><a href="#visualizacion-de-reglas" id="toc-visualizacion-de-reglas" class="nav-link" data-scroll-target="#visualizacion-de-reglas"><span class="header-section-number">3.5</span> Visualizacion de reglas</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Reglas de Asociación y Modelos de Clasificación</h1>
<p class="subtitle lead">Descubrimiento de patrones y modelos predictivos en datos de personas desaparecidas en México</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="introducción" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introducción</h1>
<section id="contexto-del-problema" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="contexto-del-problema"><span class="header-section-number">1.1</span> Contexto del problema</h2>
<p>Los derechos humanos buscan asegurar la dignidad de las personas, su propósito radica en salvaguardar y garantizar el bien común sin discriminar por raza, sexo, religión, edad, ideologías, entre otros aspectos. Asimismo, el reconocimiento de los derechos humanos a partir de 1948 (proclamados en la Declaración Universal de los Derechos Humanos por la ONU) señala derechos inherentes a los individuos por el hecho de ser humanos, proporcionando una protección a no sufrir tratos crueles, inhumanos o degradantes.</p>
<p>La desaparición de personas es un problema de seguridad y justicia, es un fenómeno que viola la dignidad del ser humano, la cual se basa en el reconocimiento de la libertad e igualdad en sus derechos. Esta privación de libertad atenta contra los derechos humanos de las personas, afecta a las víctimas y a sus familias, sembrando miedo e incertidumbre en la sociedad.</p>
<p>México es un país que alberga tradiciones y costumbres inigualables, sin embargo, no está exento de ser afectado por la violencia. Los índices de violencia han incrementado con el tiempo y se ha normalizado este fenómeno provocando falta de empatía y solidaridad en la sociedad, evidenciando la desigualdad. Con esto, la desaparición de personas en México ha experimentado un aumento constante y alarmante, generando una profunda crisis de derechos humanos.</p>
<p>Como continuación del análisis anterior sobre conjuntos de datos de los registros de estas desapariciones, en el presente trabajo buscamos continuar aplicando técnicas de minería de datos para encontrar reglas de asociación y construir modelos de clasificación que nos ayuden a encontrar nuevos patrones e información que aporte nuevas perspectivas de esta problemática.</p>
<p>Además, en el desarrollo de este trabajo reconocemos la importancia de este tema que nos incumbe a todos como humanidad, es un tema que ha sembrado desesperanza no sólo en México, sino en varias partes del mundo, es por ello que lo debemos tratar con la delicadeza y detalle que merece.</p>
</section>
<section id="objetivos" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="objetivos"><span class="header-section-number">1.2</span> Objetivos</h2>
<p>Aplicar técnicas fundamentales de minería de datos (específicamente el descubrimiento de reglas de asociación y la construcción de modelos de clasificación) sobre un conjunto de datos real y limpio de personas desaparecidas. El propósito central es extraer patrones subyacentes e implementar predicciones automatizadas, evaluando críticamente tanto el rendimiento técnico de los algoritmos como las implicaciones del mundo real y los posibles sesgos presentes en el sistema de registro.</p>
</section>
<section id="descripción-del-dataset" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="descripción-del-dataset"><span class="header-section-number">1.3</span> Descripción del dataset</h2>
<p>Para cumplir con los objetivos del presente trabajo contamos con un archivo que contiene información de los registros de personas desaparecidas en México. En total hay <strong>133,887 registros</strong> (que pueden contener campos vacíos), para cada uno de ellos hay 11 variables (características de cada registro).</p>
<p>Los campos con los que cuenta cada registro son los siguientes:</p>
<div id="tbl-descripciondataset" class="quarto-float quarto-figure quarto-figure-center anchored" data-tbl-colwidths="[20,50,15,15]">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-descripciondataset-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Diccionario de datos del registro de víctimas
</figcaption>
<div aria-describedby="tbl-descripciondataset-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 50%">
<col style="width: 15%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Nombre de columna</th>
<th style="text-align: left;">Descripción</th>
<th style="text-align: center;">Tipo de dato</th>
<th style="text-align: center;">Datos no nulos</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">id_victima</td>
<td style="text-align: left;">Identificador único alfanumérico asignado a cada registro. Variable cualitativa nominal.</td>
<td style="text-align: center;">string</td>
<td style="text-align: center;">133,887</td>
</tr>
<tr class="even">
<td style="text-align: left;">origen_reporte</td>
<td style="text-align: left;">Institución, fiscalía o comisión de búsqueda que emite o registra el caso. Variable cualitativa nominal.</td>
<td style="text-align: center;">string</td>
<td style="text-align: center;">133,887</td>
</tr>
<tr class="odd">
<td style="text-align: left;">fecha_nacimiento</td>
<td style="text-align: left;">Día, mes y año en el que nació la persona. Variable cualitativa.</td>
<td style="text-align: center;">datetime</td>
<td style="text-align: center;">105,000</td>
</tr>
<tr class="even">
<td style="text-align: left;">sexo</td>
<td style="text-align: left;">Género de la víctima: HOMBRE o MUJER. Variable cualitativa nominal.</td>
<td style="text-align: center;">string</td>
<td style="text-align: center;">133,887</td>
</tr>
<tr class="odd">
<td style="text-align: left;">fecha_desaparicion</td>
<td style="text-align: left;">Fecha y hora del último avistamiento o reporte. Variable cualitativa.</td>
<td style="text-align: center;">datetime</td>
<td style="text-align: center;">125,727</td>
</tr>
<tr class="even">
<td style="text-align: left;">fecha_registro</td>
<td style="text-align: left;">Fecha y hora de ingreso formal al sistema. Variable cualitativa.</td>
<td style="text-align: center;">datetime</td>
<td style="text-align: center;">127,790</td>
</tr>
<tr class="odd">
<td style="text-align: left;">estatus_victima</td>
<td style="text-align: left;">Condición actual de la persona en el sistema. Variable cualitativa nominal.</td>
<td style="text-align: center;">string</td>
<td style="text-align: center;">133,887</td>
</tr>
<tr class="even">
<td style="text-align: left;">cve_ent</td>
<td style="text-align: left;">Clave numérica oficial de la Entidad Federativa (INEGI). Variable cualitativa.</td>
<td style="text-align: center;">int64</td>
<td style="text-align: center;">133,887</td>
</tr>
<tr class="odd">
<td style="text-align: left;">entidad</td>
<td style="text-align: left;">Nombre del Estado de la República Mexicana. Variable cualitativa.</td>
<td style="text-align: center;">string</td>
<td style="text-align: center;">133,887</td>
</tr>
<tr class="even">
<td style="text-align: left;">cve_mun</td>
<td style="text-align: left;">Clave numérica oficial del Municipio (INEGI). Variable cualitativa.</td>
<td style="text-align: center;">int64</td>
<td style="text-align: center;">133,887</td>
</tr>
<tr class="odd">
<td style="text-align: left;">municipio</td>
<td style="text-align: left;">Nombre del municipio o alcaldía. Variable cualitativa.</td>
<td style="text-align: center;">string</td>
<td style="text-align: center;">133,887</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Con esta información podemos ver que en varios campos (id_victima, origen_reporte, sexo, estatus_victima, cve_ent, entidad, cve_mun, municipio) se cuenta con los registros completos, sin embargo, al observar los datos se identifico que muchos están completados con: CONFIDENCIAL, por lo que debemos considerar esto al realizar nuestros análisis.</p>
</section>
</section>
<section id="algoritmo-apriori" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Algoritmo Apriori</h1>
<section id="descripción" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="descripción"><span class="header-section-number">2.1</span> Descripción</h2>
<p>Este algoritmo es un método en el análisis de datos para encontrar grupos de elementos que suelen aparecer juntos en grandes conjuntos de datos. Es esencial en el descubrimiento de patrones o reglas útiles sobre cómo se relacionan los elementos.</p>
<p>Los pasos claves que implementaremos en este algoritmo son:</p>
<ol type="1">
<li><p><strong>Identificación de conjuntos de elementos frecuentes:</strong> Se examinan todos los datos para contar las apariciones de elementos y se usa el soporte mínimo para determinar si el conjunto es frecuente o no.</p></li>
<li><p><strong>Creación de un posible grupo de elementos:</strong> Tras identificar los elementos individuales que cumplieron con el soporte mínimo se combinan dichos conjuntos para crear pares y luego conjuntos de 3 y así sucesivamente hasta que no se puedan encontrar conjuntos más grandes.</p></li>
<li><p><strong>Eliminación de grupos de artículos poco frecuentes:</strong> si un grupo de elementos no aparece con la suficiente frecuencia, entonces cualquier grupo más grande que incluya estos elementos tampoco aparecerá con frecuencia.</p></li>
<li><p><strong>Generación de reglas de asociación:</strong> Se comprueban las reglas utilizando el soporte, la confianza y el lift para identificar las más fuertes.</p></li>
</ol>
<p>Para la implementación en Python de este algoritmo se crearon las siguientes funciones auxiliares:</p>
<ul>
<li><em>obtener_itemsets_frecuentes_1(transacciones, soporte_min_conteo)</em>
<ul>
<li>Está función nos ayuda a generar todos los itemsets frecuentes de tamaño 1, sólo devuelve aquellos que son considerados frecuentes, es decir, los que cumplen con el soporte mínimo. Esto nos ayuda en el primer paso del algoritmo.</li>
</ul></li>
<li><em>generar_candidatos(itemsets_frecuentes, k)</em>
<ul>
<li>Está función nos ayuda con el segundo paso de nuestro algoritmo, por lo que genera itemsets de tamaño k que pueden ser o no frecuentes, sólo genera las combinaciones a partir de la iteración anterior.</li>
</ul></li>
<li><em>filtrar_candidatos(transacciones, candidatos, soporte_min_conteo)</em>
<ul>
<li>Con esta función nos aseguramos de quedarnos únicamente los itemsets generados anteriormente que cumplan con el soporte mínimo establecido. Esto asegura nuestro tercer paso de eliminación de grupos poco frecuentes.</li>
</ul></li>
</ul>
<p>Estas funciones nos dan la pauta para la implementación completa del algoritmo apriori, el cual devuelve todos los itemsets generados. Para generar las reglas usamos otra función que recibe lo que devuelve nuestro algoritmo apriori:</p>
<ul>
<li><em>generar_reglas(itemsets_frecuentes, confianza_min)</em>
<ul>
<li>Encuentra las reglas lógicas a partir de los itemsets recibidos y consiferando el mínimo de confianza establecido.</li>
</ul></li>
</ul>
</section>
<section id="python" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="python"><span class="header-section-number">2.2</span> Python</h2>
<p>A continuación se presenta la implementación completa en Python:</p>
<div id="f29b3bfb" class="cell" data-execution_count="1">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> itertools <span class="im">import</span> combinations</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> obtener_itemsets_frecuentes_1(transacciones, soporte_min_conteo):</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co">    Escanea toda la base de datos para contar cuántas veces aparece cada elemento individualmente. </span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="co">    Luego, descarta los que no alcanzan el umbral mínimo.</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="co">    Args:</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="co">        transacciones (list): Lista de listas. Cada lista representa un registro con sus características</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="co">        soporte_min_conteo (int): Número de veces que debe aparecer un elemento para considerarlo frecuenta</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="co">    Returns:</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="co">        dict: Diccionario donde las claves son los elementos frecuentes encapsulados en un frozenset </span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="co">              y los valores son su conteo exacto</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>    conteo <span class="op">=</span> {}</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> transaccion <span class="kw">in</span> transacciones:</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> item <span class="kw">in</span> transaccion:</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>            <span class="co"># Usamos frozenset para poder usar el set como llave en el diccionario</span></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>            llave <span class="op">=</span> <span class="bu">frozenset</span>([item])</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>            conteo[llave] <span class="op">=</span> conteo.get(llave, <span class="dv">0</span>) <span class="op">+</span> <span class="dv">1</span></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>            </span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Filtramos por el soporte mínimo</span></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> {itemset: count <span class="cf">for</span> itemset, count <span class="kw">in</span> conteo.items() <span class="cf">if</span> count <span class="op">&gt;=</span> soporte_min_conteo}</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> generar_candidatos(itemsets_frecuentes, k):</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""</span></span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a><span class="co">    Toma los conjuntos frecuentes del paso anterior (tamaño k-1) y los combina entre sí para crear </span></span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a><span class="co">    nuevos grupos candidatos más grandes (de tamaño k).</span></span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a><span class="co">    Args:</span></span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a><span class="co">        itemsets_frecuentes (dict): Diccionario de elementos frecuentes</span></span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a><span class="co">        k (int): Tamaño de los nuevos conjuntos</span></span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a><span class="co">    Returns:</span></span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a><span class="co">        set: Conjunto que contiene múltiples frozenset de tamaño k, es importante aclarar que aquí son</span></span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a><span class="co">             candidatos, aún no se confirma si son frecuentes</span></span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a>    candidatos <span class="op">=</span> <span class="bu">set</span>()</span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a>    lista_itemsets <span class="op">=</span> <span class="bu">list</span>(itemsets_frecuentes.keys())</span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="bu">len</span>(lista_itemsets)):</span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> j <span class="kw">in</span> <span class="bu">range</span>(i <span class="op">+</span> <span class="dv">1</span>, <span class="bu">len</span>(lista_itemsets)):</span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a>            <span class="co"># Unimos dos itemsets</span></span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a>            union <span class="op">=</span> lista_itemsets[i] <span class="op">|</span> lista_itemsets[j]</span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a>            <span class="co"># Si el tamaño de la unión es exactamente k, es un candidato válido</span></span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a>            <span class="cf">if</span> <span class="bu">len</span>(union) <span class="op">==</span> k:</span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a>                candidatos.add(union)</span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> candidatos</span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> filtrar_candidatos(transacciones, candidatos, soporte_min_conteo):</span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""</span></span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a><span class="co">    Escanea la base de datos completa para ver cuántas veces aparecen juntos realmente los elementos de cada </span></span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a><span class="co">    conjunto candidato.</span></span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a><span class="co">    Args:</span></span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a><span class="co">        transacciones (list): Base de datos</span></span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a><span class="co">        candidatos (set): Conjunto de candidatos a revisar</span></span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a><span class="co">        soporte_min_conteo (int): Número de veces que debe aparecer un elemento para considerarlo frecuenta</span></span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a><span class="co">    Returns:</span></span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a><span class="co">        dict: Diccionario con los candidatos que su conteo fue mayor o igual a soporte_min_conteo</span></span>
<span id="cb1-67"><a href="#cb1-67" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a>    conteo <span class="op">=</span> {candidato: <span class="dv">0</span> <span class="cf">for</span> candidato <span class="kw">in</span> candidatos}</span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb1-70"><a href="#cb1-70" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> transaccion <span class="kw">in</span> transacciones:</span>
<span id="cb1-71"><a href="#cb1-71" aria-hidden="true" tabindex="-1"></a>        transaccion_set <span class="op">=</span> <span class="bu">set</span>(transaccion)</span>
<span id="cb1-72"><a href="#cb1-72" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> candidato <span class="kw">in</span> candidatos:</span>
<span id="cb1-73"><a href="#cb1-73" aria-hidden="true" tabindex="-1"></a>            <span class="cf">if</span> candidato.issubset(transaccion_set):</span>
<span id="cb1-74"><a href="#cb1-74" aria-hidden="true" tabindex="-1"></a>                conteo[candidato] <span class="op">+=</span> <span class="dv">1</span></span>
<span id="cb1-75"><a href="#cb1-75" aria-hidden="true" tabindex="-1"></a>                </span>
<span id="cb1-76"><a href="#cb1-76" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> {itemset: count <span class="cf">for</span> itemset, count <span class="kw">in</span> conteo.items() <span class="cf">if</span> count <span class="op">&gt;=</span> soporte_min_conteo}</span>
<span id="cb1-77"><a href="#cb1-77" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-78"><a href="#cb1-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-79"><a href="#cb1-79" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> algoritmo_apriori(transacciones, soporte_min<span class="op">=</span><span class="fl">0.1</span>):</span>
<span id="cb1-80"><a href="#cb1-80" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""</span></span>
<span id="cb1-81"><a href="#cb1-81" aria-hidden="true" tabindex="-1"></a><span class="co">    Encuentra grupos de elementos que suelen aparecer juntos en grandes conjuntos de datos.</span></span>
<span id="cb1-82"><a href="#cb1-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-83"><a href="#cb1-83" aria-hidden="true" tabindex="-1"></a><span class="co">    Args:</span></span>
<span id="cb1-84"><a href="#cb1-84" aria-hidden="true" tabindex="-1"></a><span class="co">        transacciones (list): Base de datos con las transacciones</span></span>
<span id="cb1-85"><a href="#cb1-85" aria-hidden="true" tabindex="-1"></a><span class="co">        min_support (float, optional): Porcentaje de soporte mínimo deseado. Defaults to 0.1.</span></span>
<span id="cb1-86"><a href="#cb1-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-87"><a href="#cb1-87" aria-hidden="true" tabindex="-1"></a><span class="co">    Returns:</span></span>
<span id="cb1-88"><a href="#cb1-88" aria-hidden="true" tabindex="-1"></a><span class="co">        dict: Diccionario que contiene todos los conjuntos frecuentes encontrados de cualquier tamaño </span></span>
<span id="cb1-89"><a href="#cb1-89" aria-hidden="true" tabindex="-1"></a><span class="co">              y su respectivo porcentaje de aparición (de 0 a 1).</span></span>
<span id="cb1-90"><a href="#cb1-90" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb1-91"><a href="#cb1-91" aria-hidden="true" tabindex="-1"></a>    total_transacciones <span class="op">=</span> <span class="bu">len</span>(transacciones)</span>
<span id="cb1-92"><a href="#cb1-92" aria-hidden="true" tabindex="-1"></a>    min_support_count <span class="op">=</span> soporte_min <span class="op">*</span> total_transacciones</span>
<span id="cb1-93"><a href="#cb1-93" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb1-94"><a href="#cb1-94" aria-hidden="true" tabindex="-1"></a>    itemsets_todos <span class="op">=</span> {}</span>
<span id="cb1-95"><a href="#cb1-95" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb1-96"><a href="#cb1-96" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Obtener frecuentes de tamaño 1</span></span>
<span id="cb1-97"><a href="#cb1-97" aria-hidden="true" tabindex="-1"></a>    itemsets_k <span class="op">=</span> obtener_itemsets_frecuentes_1(transacciones, min_support_count)</span>
<span id="cb1-98"><a href="#cb1-98" aria-hidden="true" tabindex="-1"></a>    itemsets_todos.update(itemsets_k)</span>
<span id="cb1-99"><a href="#cb1-99" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb1-100"><a href="#cb1-100" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Bucle para k = 2, 3, 4...</span></span>
<span id="cb1-101"><a href="#cb1-101" aria-hidden="true" tabindex="-1"></a>    k <span class="op">=</span> <span class="dv">2</span></span>
<span id="cb1-102"><a href="#cb1-102" aria-hidden="true" tabindex="-1"></a>    <span class="cf">while</span> itemsets_k:</span>
<span id="cb1-103"><a href="#cb1-103" aria-hidden="true" tabindex="-1"></a>        candidatos <span class="op">=</span> generar_candidatos(itemsets_k, k)</span>
<span id="cb1-104"><a href="#cb1-104" aria-hidden="true" tabindex="-1"></a>        itemsets_k <span class="op">=</span> filtrar_candidatos(transacciones, candidatos, min_support_count)</span>
<span id="cb1-105"><a href="#cb1-105" aria-hidden="true" tabindex="-1"></a>        itemsets_todos.update(itemsets_k)</span>
<span id="cb1-106"><a href="#cb1-106" aria-hidden="true" tabindex="-1"></a>        k <span class="op">+=</span> <span class="dv">1</span></span>
<span id="cb1-107"><a href="#cb1-107" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb1-108"><a href="#cb1-108" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Devolvemos los itemsets con su soporte en porcentaje (0 a 1)</span></span>
<span id="cb1-109"><a href="#cb1-109" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> {itemset: count <span class="op">/</span> total_transacciones <span class="cf">for</span> itemset, count <span class="kw">in</span> itemsets_todos.items()}</span>
<span id="cb1-110"><a href="#cb1-110" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-111"><a href="#cb1-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-112"><a href="#cb1-112" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> generar_reglas(itemsets_frecuentes, confianza_min):</span>
<span id="cb1-113"><a href="#cb1-113" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Toma los conjuntos de elementos frecuentes y aplica probabilidad condicional para encontrar reglas lógicas.</span></span>
<span id="cb1-114"><a href="#cb1-114" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-115"><a href="#cb1-115" aria-hidden="true" tabindex="-1"></a><span class="co">    Args:</span></span>
<span id="cb1-116"><a href="#cb1-116" aria-hidden="true" tabindex="-1"></a><span class="co">        itemsets_frecuentes (dict): Diccionario generado por el algoritmo apriori</span></span>
<span id="cb1-117"><a href="#cb1-117" aria-hidden="true" tabindex="-1"></a><span class="co">        confianza_min (float): El umbral mínimo de certeza que debe tener la regla</span></span>
<span id="cb1-118"><a href="#cb1-118" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-119"><a href="#cb1-119" aria-hidden="true" tabindex="-1"></a><span class="co">    Returns:</span></span>
<span id="cb1-120"><a href="#cb1-120" aria-hidden="true" tabindex="-1"></a><span class="co">        pandas.DataFrame: Tabla estructurada y ordenada con las reglas de asociación</span></span>
<span id="cb1-121"><a href="#cb1-121" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb1-122"><a href="#cb1-122" aria-hidden="true" tabindex="-1"></a>    reglas <span class="op">=</span> []</span>
<span id="cb1-123"><a href="#cb1-123" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb1-124"><a href="#cb1-124" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Para cada itemset frecuente encontrado en apriori</span></span>
<span id="cb1-125"><a href="#cb1-125" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> itemset, support <span class="kw">in</span> itemsets_frecuentes.items():</span>
<span id="cb1-126"><a href="#cb1-126" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> <span class="bu">len</span>(itemset) <span class="op">&gt;</span> <span class="dv">1</span>:</span>
<span id="cb1-127"><a href="#cb1-127" aria-hidden="true" tabindex="-1"></a>            <span class="co"># Iteramos para crear todas las combinaciones posibles de antecedente -&gt; consecuente</span></span>
<span id="cb1-128"><a href="#cb1-128" aria-hidden="true" tabindex="-1"></a>            <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">1</span>, <span class="bu">len</span>(itemset)):</span>
<span id="cb1-129"><a href="#cb1-129" aria-hidden="true" tabindex="-1"></a>                <span class="cf">for</span> antecedente <span class="kw">in</span> combinations(itemset, i):</span>
<span id="cb1-130"><a href="#cb1-130" aria-hidden="true" tabindex="-1"></a>                    antecedente <span class="op">=</span> <span class="bu">frozenset</span>(antecedente)</span>
<span id="cb1-131"><a href="#cb1-131" aria-hidden="true" tabindex="-1"></a>                    consecuente <span class="op">=</span> itemset <span class="op">-</span> antecedente</span>
<span id="cb1-132"><a href="#cb1-132" aria-hidden="true" tabindex="-1"></a>                    </span>
<span id="cb1-133"><a href="#cb1-133" aria-hidden="true" tabindex="-1"></a>                    soporte_antecedente <span class="op">=</span> itemsets_frecuentes[antecedente]</span>
<span id="cb1-134"><a href="#cb1-134" aria-hidden="true" tabindex="-1"></a>                    confianza <span class="op">=</span> support <span class="op">/</span> soporte_antecedente</span>
<span id="cb1-135"><a href="#cb1-135" aria-hidden="true" tabindex="-1"></a>                    </span>
<span id="cb1-136"><a href="#cb1-136" aria-hidden="true" tabindex="-1"></a>                    <span class="cf">if</span> confianza <span class="op">&gt;=</span> confianza_min:</span>
<span id="cb1-137"><a href="#cb1-137" aria-hidden="true" tabindex="-1"></a>                        soporte_consecuente <span class="op">=</span> itemsets_frecuentes[consecuente]</span>
<span id="cb1-138"><a href="#cb1-138" aria-hidden="true" tabindex="-1"></a>                        lift <span class="op">=</span> confianza <span class="op">/</span> soporte_consecuente</span>
<span id="cb1-139"><a href="#cb1-139" aria-hidden="true" tabindex="-1"></a>                        </span>
<span id="cb1-140"><a href="#cb1-140" aria-hidden="true" tabindex="-1"></a>                        reglas.append({</span>
<span id="cb1-141"><a href="#cb1-141" aria-hidden="true" tabindex="-1"></a>                            <span class="st">'Antecedente'</span>: <span class="bu">set</span>(antecedente),</span>
<span id="cb1-142"><a href="#cb1-142" aria-hidden="true" tabindex="-1"></a>                            <span class="st">'Consecuente'</span>: <span class="bu">set</span>(consecuente),</span>
<span id="cb1-143"><a href="#cb1-143" aria-hidden="true" tabindex="-1"></a>                            <span class="st">'Soporte'</span>: support,</span>
<span id="cb1-144"><a href="#cb1-144" aria-hidden="true" tabindex="-1"></a>                            <span class="st">'Confianza'</span>: confianza,</span>
<span id="cb1-145"><a href="#cb1-145" aria-hidden="true" tabindex="-1"></a>                            <span class="st">'Lift'</span>: lift</span>
<span id="cb1-146"><a href="#cb1-146" aria-hidden="true" tabindex="-1"></a>                        })</span>
<span id="cb1-147"><a href="#cb1-147" aria-hidden="true" tabindex="-1"></a>                        </span>
<span id="cb1-148"><a href="#cb1-148" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> pd.DataFrame(reglas).sort_values(by<span class="op">=</span><span class="st">'Lift'</span>, ascending<span class="op">=</span><span class="va">False</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>En adición al algoritmo se anexa una función para obtener la lista de transacciones de una base de datos a partir de un dataframe, esto para poder facilitar los siguientes análisis a nuestro conjunto de datos sobre los registros de personas desaparecidas en México:</p>
<div id="97680e49" class="cell" data-execution_count="2">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> df_a_transacciones(df):</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="co">    Convierte un DataFrame de Pandas en una lista de transacciones (lista de listas)</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co">    formateada para el algoritmo apriori.</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="co">    </span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="co">    Args:</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="co">        df (pd.DataFrame): El DataFrame con los datos originales.</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="co">    </span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="co">    Returns:</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="co">        list: Una lista de listas lista que representa las transacciones del dataframe</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>    columnas <span class="op">=</span> df.columns.tolist()</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>    transacciones <span class="op">=</span> []</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> index, fila <span class="kw">in</span> df.iterrows():</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>        transaccion <span class="op">=</span> [<span class="ss">f"</span><span class="sc">{</span>col<span class="sc">}</span><span class="ss">=</span><span class="sc">{</span>fila[col]<span class="sc">}</span><span class="ss">"</span> <span class="cf">for</span> col <span class="kw">in</span> columnas]</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>        transacciones.append(transaccion)</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>            </span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> transacciones</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
</section>
<section id="descubrimiento-de-patrones-reglas-de-asociación" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Descubrimiento de patrones: Reglas de Asociación</h1>
<section id="conocimiento-de-la-problemática" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="conocimiento-de-la-problemática"><span class="header-section-number">3.1</span> Conocimiento de la problemática</h2>
<p>Como se definió en la sección de Objetivo del proyecto, se cuenta con un conjunto de datos reales relacionados con la desaparición de personas en México. A partir de ello, se busca identificar información relevante dentro del conjunto de datos, es decir, subconjuntos de variables que presenten algún tipo de correlación. En este contexto, el objetivo es encontrar relaciones del tipo X ⇒ Y, conocidas como patrones, las cuales constituyen el eje principal del aprendizaje no supervisado.</p>
<p>Estos patrones permiten extraer conocimiento útil a partir de los datos disponibles. Por ejemplo, una regla como (SEXO = MUJER, EDAD = 17 ⇒ ENTIDAD_FEDERATIVA = X) podría ayudar a responder preguntas como: ¿en qué entidad federativa es más probable que desaparezca una mujer de 17 años?</p>
<p>El objetivo principal es construir un modelo basado en reglas de asociación no triviales. A lo largo del proceso, dichas reglas podrán ajustarse y refinarse, con la finalidad de obtener resultados más precisos y relevantes, facilitando así su interpretación y análisis.</p>
</section>
<section id="analitica-y-preparacion-de-datos" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="analitica-y-preparacion-de-datos"><span class="header-section-number">3.2</span> Analitica y preparacion de datos</h2>
<p>El conjunto de datos con el que se trabaja consta de <strong>133,887 registros</strong>. Para aplicar el algoritmo Apriori, es necesario transformar primero los datos a un formato transaccional. Este proceso se realiza mediante la función <code>df_a_transacciones()</code>, definida en la sección anterior, mientras que la función <code>algoritmo_apriori()</code> permite operar sobre dichas transacciones.</p>
<p>En este contexto, cada <strong>transacción</strong> corresponde a un registro del conjunto de datos, es decir, a la información asociada a una persona desaparecida. Internamente, las transacciones se representan mediante una <strong>matriz binaria</strong>, donde cada fila corresponde a una transacción y cada columna a un <em>ítem</em> (atributo en forma categórica).</p>
<p>En esta matriz, se asigna el valor <strong>1 (True)</strong> en la posición <em>(i, j)</em> si la transacción <em>i</em> contiene el ítem <em>j</em>, y <strong>0 (False)</strong> en caso contrario. Esta representación permite identificar de manera eficiente la presencia o ausencia de atributos en cada registro.</p>
<p>En el siguiente listado se muestra el código necesario para construir dicha matriz binaria, cuya importancia radica en que constituye el punto de entrada para algoritmos de minería de datos como Apriori, los cuales permiten posteriormente generar reglas de asociación.</p>
<div id="8fab5b21" class="cell" data-execution_count="3">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> mlxtend.preprocessing <span class="im">import</span> TransactionEncoder</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>frame <span class="op">=</span> pd.read_csv(<span class="st">"data_secretariado.csv"</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>transacciones <span class="op">=</span> df_a_transacciones(frame)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>codificador <span class="op">=</span> TransactionEncoder()</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>transacciones_codificadas <span class="op">=</span> codificador.fit_transform(transacciones)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>transacciones_codificadas <span class="op">=</span> pd.DataFrame(transacciones_codificadas, columns<span class="op">=</span>codificador.columns_)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>transacciones_codificadas</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="tbl-cap">
<p>Vista parcial del conjunto de datos transformado a formato transaccional (one-hot encoding)</p>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 5%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 3%">
<col style="width: 22%">
<col style="width: 3%">
<col style="width: 14%">
<col style="width: 10%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">index</th>
<th style="text-align: center;">CVE_ENT=10</th>
<th style="text-align: center;">CVE_ENT=11</th>
<th style="text-align: center;">CVE_ENT=13</th>
<th style="text-align: center;">…</th>
<th style="text-align: center;">ORIGEN_REPORTE=SE DESCONOCE</th>
<th style="text-align: center;">…</th>
<th style="text-align: center;">SEXO=CONFIDENCIAL</th>
<th style="text-align: center;">SEXO=HOMBRE</th>
<th style="text-align: center;">SEXO=MUJER</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0</td>
<td style="text-align: center;">True</td>
<td style="text-align: center;">False</td>
<td style="text-align: center;">False</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">False</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">True</td>
<td style="text-align: center;">False</td>
<td style="text-align: center;">False</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: center;">False</td>
<td style="text-align: center;">False</td>
<td style="text-align: center;">False</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">False</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">False</td>
<td style="text-align: center;">True</td>
<td style="text-align: center;">False</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2</td>
<td style="text-align: center;">False</td>
<td style="text-align: center;">False</td>
<td style="text-align: center;">False</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">False</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">True</td>
<td style="text-align: center;">False</td>
<td style="text-align: center;">False</td>
</tr>
<tr class="even">
<td style="text-align: right;">3</td>
<td style="text-align: center;">False</td>
<td style="text-align: center;">False</td>
<td style="text-align: center;">False</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">False</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">True</td>
<td style="text-align: center;">False</td>
<td style="text-align: center;">False</td>
</tr>
<tr class="odd">
<td style="text-align: right;">4</td>
<td style="text-align: center;">False</td>
<td style="text-align: center;">False</td>
<td style="text-align: center;">False</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">False</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">True</td>
<td style="text-align: center;">False</td>
<td style="text-align: center;">False</td>
</tr>
<tr class="even">
<td style="text-align: right;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
</tr>
<tr class="odd">
<td style="text-align: right;">133882</td>
<td style="text-align: center;">False</td>
<td style="text-align: center;">True</td>
<td style="text-align: center;">False</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">False</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">False</td>
<td style="text-align: center;">True</td>
<td style="text-align: center;">False</td>
</tr>
<tr class="even">
<td style="text-align: right;">133883</td>
<td style="text-align: center;">False</td>
<td style="text-align: center;">False</td>
<td style="text-align: center;">True</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">False</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">False</td>
<td style="text-align: center;">False</td>
<td style="text-align: center;">True</td>
</tr>
<tr class="odd">
<td style="text-align: right;">133884</td>
<td style="text-align: center;">False</td>
<td style="text-align: center;">False</td>
<td style="text-align: center;">False</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">False</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">False</td>
<td style="text-align: center;">True</td>
<td style="text-align: center;">False</td>
</tr>
</tbody>
</table>
<p>Como se puede observar, para cada elemento <em>(i, j)</em> se asignan valores <strong>0/1 (False/True)</strong> dependiendo de si el ítem <em>j</em> está presente en la transacción <em>i</em>. Esta representación puede interpretarse de la siguiente manera: por ejemplo, si se tiene <em>(index = 1, SEXO=HOMBRE = True)</em>, esto indica que la transacción correspondiente al registro 1 pertenece a una persona desaparecida de sexo masculino. De igual manera, podemos sacar mas informacion con respecto a las transacciones, como:</p>
<div id="f9bec2fd" class="cell" data-execution_count="4">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>numero_transacciones <span class="op">=</span> <span class="bu">len</span>(transacciones_codificadas)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>dimensiones <span class="op">=</span> transacciones_codificadas.shape</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>numero_items <span class="op">=</span> transacciones_codificadas.shape[<span class="dv">1</span>]</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>proporcion <span class="op">=</span> transacciones_codificadas.to_numpy().mean()</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'numero de transacciones : </span><span class="sc">{</span>numero_transacciones<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'dimensiones : </span><span class="sc">{</span>dimensiones<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'items distintos : </span><span class="sc">{</span>numero_items<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Presencia de items : </span><span class="sc">{</span><span class="bu">round</span>(proporcion, <span class="dv">6</span>)<span class="sc">}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<pre class="output"><code>numero de transacciones : 131715
dimensiones : (131715, 255842)
items distintos : 255842
Presencia de items : 4.3e-05 </code></pre>
<p>En principio, se observa un aspecto relevante: la cantidad de ítems en la matriz es extremadamente alta, alcanzando aproximadamente <strong>255,000 ítems distintos</strong>. A partir de este volumen, se obtiene que la proporción de ítems presentes por transacción es muy baja, lo que indica una <strong>alta dispersión (sparsity)</strong> en los datos.</p>
<p>En otras palabras, la mayoría de las transacciones contienen muy pocos ítems en relación con el total disponible, lo que implica que predominan los valores de ausencia (<em>False</em>) sobre los de presencia (<em>True</em>). Esta situación representa un reto importante al aplicar el algoritmo de reglas de asociación, ya que puede afectar tanto la eficiencia computacional como la calidad de los resultados.</p>
<p>Si se utiliza el conjunto de datos sin ningún tipo de tratamiento previo, es probable que muchas de las reglas generadas sean triviales o poco informativas. Esto se debe a que el algoritmo puede identificar relaciones que, aunque cumplen con los criterios de soporte y confianza, no aportan conocimiento significativo. Además, el alto número de ítems incrementa considerablemente el costo computacional del proceso.</p>
<section id="preparación-de-datos" class="level3" data-number="3.2.1">
<h3 data-number="3.2.1" class="anchored" data-anchor-id="preparación-de-datos"><span class="header-section-number">3.2.1</span> Preparación de datos</h3>
<p>Durante la inspección del conjunto de datos, se identificaron atributos que no aportan valor para la generación de reglas de asociación. Un ejemplo de ello es el atributo <code>ID_VICTIMA</code>, el cual corresponde a un identificador único por registro. Debido a su <strong>naturaleza no repetitiva</strong>, este tipo de variable no contribuye a la generación de patrones frecuentes, por lo que se optó por eliminarlo.</p>
<p>De manera similar, las variables codificadas como <code>CVE_ENT</code> o <code>CVE_MUN</code> representan la misma información que atributos categóricos como <code>ENTIDAD_FEDERATIVA</code> y <code>MUNICIPIO</code>. La inclusión simultánea de ambas representaciones introduce <strong>redundancia</strong> en los datos y puede dar lugar a reglas triviales (por ejemplo, equivalencias directas entre códigos y nombres).</p>
<p>Por esta razón, se decidió conservar únicamente las variables categóricas nominales (<code>ENTIDAD_FEDERATIVA</code> y <code>MUNICIPIO</code>), ya que proporcionan una interpretación más clara y descriptiva, y eliminar las variables codificadas correspondientes. Esta decisión contribuye a reducir la dimensionalidad del conjunto de datos y a mejorar la calidad de las reglas generadas. Como primer paso, se realiza la <strong>discretización de variables continuas</strong>, especialmente aquellas que, debido a su alta granularidad, pueden incrementar significativamente la dimensionalidad de la matriz binaria generada en el preprocesamiento. Un caso representativo es el de las variables de tipo fecha.</p>
<p>En particular, la variable <code>FECHA_NACIMIENTO</code> no aporta directamente un valor semántico relevante para la generación de patrones; sin embargo, puede utilizarse como base para derivar una nueva variable más significativa: la <strong>edad</strong>. Esta se obtiene a partir de la diferencia entre <code>FECHA_DESAPARICION</code> y <code>FECHA_NACIMIENTO</code>, permitiendo representar de forma más adecuada las características demográficas de los registros.</p>
<p>Adicionalmente, se identificó que las variables temporales pueden contener patrones relevantes a nivel de agregación. Por ello, la variable <code>FECHA_DESAPARICION</code> se descompone en componentes de <strong>año</strong> y <strong>mes</strong>, descartando el día. Esta decisión se justifica en que el día introduce una alta variabilidad (alta cardinalidad), lo que incrementa innecesariamente el número de ítems sin aportar, en la mayoría de los casos, información significativa para el descubrimiento de patrones.</p>
<p>Este proceso refleja una consideración importante en el uso de reglas de asociación: el rendimiento y la calidad de los patrones obtenidos dependen en gran medida del control de la <strong>dimensionalidad del espacio de ítems</strong>. Variables continuas con amplios rangos tienden a generar una gran cantidad de valores únicos, lo que se traduce en una matriz altamente dispersa y en una reducción de la efectividad del algoritmo.</p>
<p>Por esta razón, se opta por discretizar variables como la edad (agrupándola en rangos) y transformar las variables de fecha, conservando únicamente componentes como el mes y el año. Estas decisiones permiten reducir la dimensionalidad, mejorar la interpretabilidad de los resultados y facilitar la generación de reglas de asociación más relevantes.</p>
</section>
<section id="tratamiento-de-datos-faltantes-mcar-vs-mar" class="level3" data-number="3.2.2">
<h3 data-number="3.2.2" class="anchored" data-anchor-id="tratamiento-de-datos-faltantes-mcar-vs-mar"><span class="header-section-number">3.2.2</span> Tratamiento de datos faltantes (MCAR vs MAR)</h3>
<p>En el análisis de datos es fundamental identificar la naturaleza de los valores faltantes (representados como <em>NaN</em> en <em>pandas</em>) y definir estrategias adecuadas para su tratamiento. En el conjunto de datos analizado, de un total de <strong>133,887 registros</strong>, aproximadamente <strong>34,964</strong> presentan al menos un valor faltante en variables categóricas relevantes para el descubrimiento de patrones, particularmente aquellas relacionadas con <code>FECHA_NACIMIENTO</code>, <code>FECHA_DESAPARICION</code> y <code>FECHA_REGISTRO</code>.</p>
<p>Considerando que estas variables son clave para la generación de atributos derivados (como la edad o componentes temporales), la imputación de valores —ya sea mediante moda en variables categóricas o técnicas como KNN— puede introducir sesgos significativos. En el contexto de reglas de asociación, este problema es especialmente crítico, ya que dichas técnicas se basan en la frecuencia de co-ocurrencia de los ítems.</p>
<p>En particular, la imputación puede alterar artificialmente métricas como el <strong>soporte</strong>, la <strong>confianza</strong> y el <strong>lift</strong>, inflando la frecuencia de ciertos patrones y generando reglas que no reflejan relaciones reales en los datos. Dado que estas métricas se interpretan en términos de probabilidades condicionadas, condicionar sobre datos imputados puede distorsionar la interpretación de los resultados y comprometer la validez del análisis.</p>
<p>Por otro lado, la proporción de datos completos (~74%) sigue siendo suficientemente representativa para la identificación de patrones relevantes. En este sentido, se opta por evitar la imputación y trabajar con un enfoque de <strong>análisis de casos completos</strong>, priorizando la integridad de los datos observados.</p>
<p>A continuación, se describe el proceso de preprocesamiento de la información:</p>
<div id="36fe8e92" class="cell" data-execution_count="5">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Creamos una copia para no afectar el dataframe original antes de la limpieza</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>df_analysis <span class="op">=</span> frame.copy()</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Creamos indicadores booleanos de nulos para las fechas</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>df_analysis[<span class="st">'FECHA_DESAPARICION_NULL'</span>] <span class="op">=</span> df_analysis[<span class="st">'FECHA_DESAPARICION'</span>].isna()</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>df_analysis[<span class="st">'FECHA_NACIMIENTO_NULL'</span>] <span class="op">=</span> df_analysis[<span class="st">'FECHA_NACIMIENTO'</span>].isna()</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Análisis por SEXO</span></span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>missing_by_sex <span class="op">=</span> df_analysis.groupby(<span class="st">'SEXO'</span>)[[<span class="st">'FECHA_DESAPARICION_NULL'</span>, <span class="st">'FECHA_NACIMIENTO_NULL'</span>]].mean()</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Análisis por ENTIDAD (Top 15 con más registros para mejor visualización)</span></span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>top_entidades <span class="op">=</span> df_analysis[<span class="st">'ENTIDAD'</span>].value_counts().nlargest(<span class="dv">15</span>).index</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>df_top_entidades <span class="op">=</span> df_analysis[df_analysis[<span class="st">'ENTIDAD'</span>].isin(top_entidades)]</span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>missing_by_entidad <span class="op">=</span> df_top_entidades.groupby(<span class="st">'ENTIDAD'</span>)[[<span class="st">'FECHA_DESAPARICION_NULL'</span>, <span class="st">'FECHA_NACIMIENTO_NULL'</span>]].mean()</span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualización</span></span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">16</span>, <span class="dv">6</span>))</span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a>sns.heatmap(missing_by_sex, annot<span class="op">=</span><span class="va">True</span>, cmap<span class="op">=</span><span class="st">'YlGnBu'</span>, ax<span class="op">=</span>axes[<span class="dv">0</span>])</span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_title(<span class="st">'Proporción de Nulos por SEXO'</span>)</span>
<span id="cb6-24"><a href="#cb6-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-25"><a href="#cb6-25" aria-hidden="true" tabindex="-1"></a>sns.heatmap(missing_by_entidad, annot<span class="op">=</span><span class="va">True</span>, cmap<span class="op">=</span><span class="st">'YlGnBu'</span>, ax<span class="op">=</span>axes[<span class="dv">1</span>])</span>
<span id="cb6-26"><a href="#cb6-26" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_title(<span class="st">'Proporción de Nulos por ENTIDAD (Top 15)'</span>)</span>
<span id="cb6-27"><a href="#cb6-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-28"><a href="#cb6-28" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb6-29"><a href="#cb6-29" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="heatmaps/MCAR_MAR.png" class="img-fluid figure-img"></p>
<figcaption>Proprocion de datos faltantes</figcaption>
</figure>
</div>
<p>A partir del análisis visual mediante el heatmap, se observa que la variable <code>FECHA_DESAPARICION</code> en valores nulos no presenta un comportamiento claramente asociado a otras variables (no evidencia fuerte de un patrón MAR). En particular, aunque se identifican ligeras concentraciones en ciertos estados, la relación general es débil, con valores promedio cercanos a <strong>0.3</strong>, lo que sugiere una baja dependencia estructural.</p>
<p>Por otro lado, la variable <code>FECHA_NACIMIENTO</code> sí muestra un comportamiento distinto. En este caso, se identifica una fuerte asociación entre la ausencia de datos y la variable <code>SEXO</code>, específicamente con la categoría <em>INDETERMINADO</em>. Esta relación se refleja en una proporción aproximada de <strong>0.83</strong>, lo que indica que:</p>
<p><span class="math display">\[
P(\text{FECHA\_NACIMIENTO} = \text{null} \mid \text{SEXO} = \text{INDETERMINADO}) \approx 0.83
\]</span></p>
<p>Este resultado sugiere un patrón consistente con un mecanismo de datos faltantes tipo MAR (Missing At Random), donde la probabilidad de ausencia depende de otra variable observada. En términos prácticos, implica que los registros correspondientes a personas con sexo indeterminado son significativamente más propensos a carecer de información sobre su fecha de nacimiento.</p>
<p>Dado que en este trabajo se opta por no realizar imputación —con el objetivo de preservar la integridad de los datos observados para el análisis mediante reglas de asociación—, se decide trabajar con un enfoque de <strong>análisis de casos completos</strong>. Sin embargo, esta decisión introduce un sesgo importante, ya que afecta de manera desproporcionada a este grupo específico de registros.</p>
<p>Por lo tanto, es importante reconocer esta situación como una de las principales limitaciones del conjunto de datos, ya que ciertos patrones asociados a este grupo podrían quedar subrepresentados en el análisis final.</p>
</section>
<section id="manejo-de-datos-confidenciales" class="level3" data-number="3.2.3">
<h3 data-number="3.2.3" class="anchored" data-anchor-id="manejo-de-datos-confidenciales"><span class="header-section-number">3.2.3</span> Manejo de datos confidenciales</h3>
<p>Otro aspecto relevante a considerar es la consistencia de la información disponible para la generación de reglas de asociación con métricas confiables. A partir del preprocesamiento, se cuenta con <strong>98,923 registros completos</strong> (sin valores nulos); sin embargo, aún persiste una limitación importante asociada a la presencia del valor <em>CONFIDENCIAL</em> en múltiples variables.</p>
<p>Este fenómeno introduce un reto adicional en el análisis, ya que puede afectar la calidad e interpretabilidad de los patrones descubiertos. En particular, resulta relevante evaluar si es posible obtener reglas significativas cuando intervienen variables con valores confidenciales, así como identificar si existen patrones de co-ocurrencia sistemáticos entre dichas variables.</p>
<p>El análisis exploratorio muestra que la confidencialidad no se distribuye de manera uniforme: mientras varias variables presentan este valor, otras como <code>ENTIDAD</code> y <code>ORIGEN_REPORTE</code> no contienen registros confidenciales. Esta característica las posiciona como variables clave para el análisis, al permitir la identificación de asociaciones más interpretables dentro del conjunto de datos.</p>
<div id="1f90f707" class="cell" data-execution_count="6">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>confidential_count <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> index, row <span class="kw">in</span> frame.iterrows():</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Si 'CONFIDENCIAL' existe en cualquier columna</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="st">'CONFIDENCIAL'</span> <span class="kw">in</span> row.values:</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>        confidential_count <span class="op">+=</span> <span class="dv">1</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Total de registros analizados: </span><span class="sc">{</span><span class="bu">len</span>(frame)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Registros con al menos un dato 'CONFIDENCIAL': </span><span class="sc">{</span>confidential_count<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Proporción sobre el total actual: </span><span class="sc">{</span><span class="bu">round</span>(confidential_count <span class="op">/</span> <span class="bu">len</span>(frame) <span class="op">*</span> <span class="dv">100</span>, <span class="dv">2</span>)<span class="sc">}</span><span class="ss">%"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<pre class="output"><code>Total de registros analizados: 98923
Registros con al menos un dato 'CONFIDENCIAL': 49149
Proporción sobre el total actual: 49.68%</code></pre>
<p>Se observa que aproximadamente el <strong>49.68%</strong> de los registros contienen al menos un valor <em>CONFIDENCIAL</em>. Este resultado indica que una proporción significativa del conjunto de datos presenta algún nivel de ocultamiento de información, lo cual puede influir en la generación y calidad de los patrones obtenidos.</p>
<p>Adicionalmente, se identifica que los valores confidenciales no aparecen de manera aislada, sino que tienden a presentarse simultáneamente en múltiples variables. En particular, se observa que <strong>5 de las 7 variables analizadas</strong> presentan valores <em>CONFIDENCIAL</em> de forma conjunta en un subconjunto considerable de registros.</p>
<p>Este comportamiento sugiere una <strong>dependencia probabilística</strong> entre dichas variables, en el sentido de que la ocurrencia de confidencialidad en una variable incrementa la probabilidad de observar el mismo valor en las demás. En términos de distribución conjunta, esto indica que estos eventos no son independientes y presentan una alta co-ocurrencia dentro de las transacciones.</p>
<div id="6101aee8" class="cell" data-execution_count="7">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>confidential_count <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> index, row <span class="kw">in</span> frame.iterrows():</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>    valor_nacimiento <span class="op">=</span> row[<span class="st">'FECHA_NACIMIENTO'</span>]</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>    valor_desaparicion <span class="op">=</span>  row[<span class="st">'FECHA_DESAPARICION'</span>]</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>    valor_registro <span class="op">=</span> row[<span class="st">'FECHA_REGISTRO'</span>]</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>    valor_municipio <span class="op">=</span> row[<span class="st">'MUNICIPIO'</span>]</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>    valor_entidad <span class="op">=</span> row[<span class="st">'ENTIDAD'</span>]</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>    valor_sexo <span class="op">=</span> row[<span class="st">'SEXO'</span>]</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>    valor_status <span class="op">=</span> row[<span class="st">'ESTATUS_VICTIMA'</span>]</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>    existe <span class="op">=</span> (valor_nacimiento <span class="op">==</span> <span class="st">'CONFIDENCIAL'</span></span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>    <span class="kw">and</span> valor_registro <span class="op">==</span> <span class="st">'CONFIDENCIAL'</span></span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>    <span class="kw">and</span> valor_municipio <span class="op">==</span> <span class="st">'CONFIDENCIAL'</span></span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>    <span class="kw">and</span> valor_sexo <span class="op">==</span> <span class="st">'CONFIDENCIAL'</span></span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>    <span class="kw">and</span> valor_status <span class="op">==</span> <span class="st">'CONFIDENCIAL'</span>)</span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> existe:</span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a>      confidential_count <span class="op">+=</span> <span class="dv">1</span></span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Total de registros analizados: </span><span class="sc">{</span><span class="bu">len</span>(frame)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb9-23"><a href="#cb9-23" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Registros con al menos un dato 'CONFIDENCIAL': </span><span class="sc">{</span>confidential_count<span class="sc">}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<pre class="output"><code>Total de registros analizados: 98923
Registros con al menos un dato 'CONFIDENCIAL': 49149</code></pre>
<p>Como se observa, <strong>5 de las 7 variables analizadas presentan valores confidenciales</strong>, y además se identifica que la proporción de registros con al menos un valor <em>CONFIDENCIAL</em> coincide con aquellos en los que estas cinco variables toman dicho valor de manera conjunta. Esto sugiere una <strong>dependencia probabilística</strong> entre dichas variables, es decir, la presencia de confidencialidad en una de ellas incrementa significativamente la probabilidad de que las demás también presenten este valor.</p>
<p>Este comportamiento permite considerar la posibilidad de encontrar reglas de asociación más complejas, particularmente en relación con las variables que no presentan este problema, como <code>ENTIDAD</code> y <code>ORIGEN_REPORTE</code>. En particular, se observa que <code>ENTIDAD</code> no contiene valores confidenciales, lo que la convierte en una variable relevante para el análisis.</p>
<p>Por otro lado, las reglas que involucren combinaciones como <code>{CONFIDENCIAL, CONFIDENCIAL}</code>, o que no aporten información significativa, son descartadas, ya que no contribuyen a la generación de conocimiento útil.</p>
<p>En este sentido, se opta por <strong>mantener el valor CONFIDENCIAL como una categoría dentro de las variables categóricas</strong>, en lugar de eliminarlo. Esta decisión permite conservar la estructura probabilística de las transacciones y evitar la pérdida de asociaciones entre variables no confidenciales, como <code>ENTIDAD</code> y <code>ORIGEN_REPORTE</code>. No obstante, se reconoce que esta elección puede introducir limitaciones en la interpretabilidad de las reglas generadas.</p>
</section>
<section id="discretizacion-de-variables-continuas" class="level3" data-number="3.2.4">
<h3 data-number="3.2.4" class="anchored" data-anchor-id="discretizacion-de-variables-continuas"><span class="header-section-number">3.2.4</span> Discretizacion de variables continuas</h3>
<p>Como se observa, el umbral de aparición de ítems distintos en la matriz binaria es muy bajo. Esto se debe, en gran medida, al manejo de variables de tipo fecha, ya que pequeñas variaciones —como diferencias en la hora— generan nuevos ítems, incrementando la dimensionalidad del espacio y reduciendo la frecuencia relativa de co-ocurrencia entre ellos.</p>
<p>Asimismo, se identifica que las variables <code>FECHA_NACIMIENTO</code> y <code>FECHA_DESAPARICION</code> funcionan como variables auxiliares para la construcción de un atributo más representativo: la <strong>edad</strong>. Esta se obtiene a partir de la diferencia entre los años de ambas fechas, permitiendo capturar patrones más interpretables asociados a grupos etarios. En consecuencia, se crea la variable <code>EDAD</code> y se elimina <code>FECHA_NACIMIENTO</code>.</p>
<p>Por su parte, la variable <code>FECHA_DESAPARICION</code>, así como <code>FECHA_REGISTRO</code>, se descomponen en componentes de <strong>año</strong> y <strong>mes</strong>, eliminando la granularidad asociada al día y la hora. Esta transformación reduce la cardinalidad de los datos y favorece la generación de patrones más generales. No obstante, estas nuevas variables requieren un proceso posterior de discretización para su adecuado uso en reglas de asociación.</p>
<p>La estrategia de transformación y construcción de variables se detalla a continuación:</p>
<div id="fac10813" class="cell" data-execution_count="8">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convertimos temporalmente a datetime para extraer el año, ignorando errores para valores como 'CONFIDENCIAL'</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>anio_desaparicion <span class="op">=</span> pd.to_datetime(frame[<span class="st">'FECHA_DESAPARICION'</span>], errors<span class="op">=</span><span class="st">'coerce'</span>).dt.year</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>anio_nacimiento <span class="op">=</span> pd.to_datetime(frame[<span class="st">'FECHA_NACIMIENTO'</span>], errors<span class="op">=</span><span class="st">'coerce'</span>).dt.year</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculamos la edad como la diferencia simple de años</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>frame[<span class="st">'EDAD'</span>] <span class="op">=</span> anio_desaparicion <span class="op">-</span> anio_nacimiento</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Posteriormente fragmentamos las fechas de las varaibles</p>
<div id="37f72e9d" class="cell" data-execution_count="9">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convertimos a datetime temporalmente para extraer componentes</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>fecha_des_dt <span class="op">=</span> pd.to_datetime(frame[<span class="st">'FECHA_DESAPARICION'</span>], errors<span class="op">=</span><span class="st">'coerce'</span>)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>fecha_reg_dt <span class="op">=</span> pd.to_datetime(frame[<span class="st">'FECHA_REGISTRO'</span>], errors<span class="op">=</span><span class="st">'coerce'</span>)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Creamos las nuevas variables categóricas</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>frame[<span class="st">'MES_DESAPARICION'</span>] <span class="op">=</span> fecha_des_dt.dt.month</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>frame[<span class="st">'ANIO_DESAPARICION'</span>] <span class="op">=</span> fecha_des_dt.dt.year</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>frame[<span class="st">'MES_REGISTRO'</span>] <span class="op">=</span> fecha_reg_dt.dt.month</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>frame[<span class="st">'ANIO_REGISTRO'</span>] <span class="op">=</span> fecha_reg_dt.dt.year</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Cuando ordenamos los valores se observa la presencia de edades negativas donde indican registros donde el año de nacimiento es mayor al año de desaparición.</p>
<div id="5580bbe5" class="cell" data-execution_count="10">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Filtrar registros con edades negativas</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>inconsistentes <span class="op">=</span> frame[frame[<span class="st">'EDAD'</span>] <span class="op">&lt;</span> <span class="dv">0</span>]</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Total de registros con edad negativa: </span><span class="sc">{</span><span class="bu">len</span>(inconsistentes)<span class="sc">}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<pre class="output"><code>Total de registros con edad negativa: 39</code></pre>
<p>Se identifican <strong>39 registros</strong> con edades negativas. Dado que su proporción es mínima respecto al total, se opta por eliminarlos. Aunque estos casos podrían estar asociados a un mecanismo de datos faltantes tipo MCAR, su impacto es reducido y su eliminación permite mantener la consistencia del conjunto de datos sin introducir sesgos derivados de imputación.</p>
<p>Adicionalmente, se observa que aproximadamente el <strong>70%</strong> de estos registros corresponden a personas de sexo masculino, lo que indica que este grupo es el más afectado por errores de captura en este subconjunto específico. Si bien esta eliminación introduce una ligera pérdida de representación para dicho grupo, su impacto global en el análisis es limitado debido a la baja proporción de estos casos.</p>
<div id="9c1e4d80" class="cell" data-execution_count="11">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>frame <span class="op">=</span> frame[<span class="op">~</span>(frame[<span class="st">'EDAD'</span>] <span class="op">&lt;</span> <span class="dv">0</span>)]</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="co">#Copiamos una referencia para graficar la distribucion continua de las edades</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>frame_continuas <span class="op">=</span> frame.copy()</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Eliminamos las columnas que tengan que ver con la fecha</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>frame <span class="op">=</span> frame.drop([<span class="st">'FECHA_DESAPARICION'</span>, <span class="st">'FECHA_REGISTRO'</span>, <span class="st">'FECHA_NACIMIENTO'</span>], axis<span class="op">=</span><span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Como se observa en el script, además de eliminar los registros inconsistentes, se genera una copia del <em>DataFrame</em> original (<code>frame_continuas</code>) con el objetivo de conservar la distribución continua de la variable <code>EDAD</code> para su posterior análisis.</p>
<p>Adicionalmente, se eliminan las variables originales de fecha (<code>FECHA_DESAPARICION</code>, <code>FECHA_REGISTRO</code>, <code>FECHA_NACIMIENTO</code>), dado que ya han sido transformadas en variables más adecuadas. Este paso contribuye a reducir la dimensionalidad del conjunto de datos y evita redundancia en la representación de la información. Una vez tratados los valores inconsistentes, se procede a discretizar la variable <code>EDAD</code> en intervalos definidos. La discretización se realiza mediante la construcción de categorías ordinales: <strong>INFANTE, ADOLESCENTE, JOVEN, ADULTO y ADULTO_MAYOR</strong>, utilizando un conjunto de <em>bins</em> no necesariamente equidistantes.</p>
<p>Adicionalmente, los valores no definidos (derivados de datos faltantes o inconsistentes previos) se agrupan bajo la categoría <em>CONFIDENCIAL</em>, manteniendo coherencia con el tratamiento general de valores confidenciales en el conjunto de datos.</p>
<div id="442868b3" class="cell" data-execution_count="12">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Definir los bins y etiquetas para la discretización</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>bins <span class="op">=</span> [<span class="dv">0</span>, <span class="dv">11</span>, <span class="dv">20</span>, <span class="dv">39</span>, <span class="dv">59</span>, <span class="bu">float</span>(<span class="st">'inf'</span>)]</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>labels <span class="op">=</span> [<span class="st">'INFANTE'</span>, <span class="st">'ADOLESCENTE'</span>, <span class="st">'JOVEN'</span>, <span class="st">'ADULTO'</span>, <span class="st">'ADULTO_MAYOR'</span>]</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Aplicar pd.cut para crear la nueva categoría</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>frame[<span class="st">'EDAD'</span>] <span class="op">=</span> pd.cut(frame[<span class="st">'EDAD'</span>], bins<span class="op">=</span>bins, labels<span class="op">=</span>labels, include_lowest<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Convertir a object o string para permitir la asignación de 'CONFIDENCIAL' a los nulos</span></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>frame[<span class="st">'EDAD'</span>] <span class="op">=</span> frame[<span class="st">'EDAD'</span>].astype(<span class="bu">object</span>).fillna(<span class="st">'CONFIDENCIAL'</span>)</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Conteo de categorías en EDAD:"</span>)</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(frame[<span class="st">'EDAD'</span>].value_counts())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<pre class="output"><code>Conteo de categorías en EDAD:
EDAD
CONFIDENCIAL    49156
JOVEN           26480
ADULTO          10765
ADOLESCENTE      7723
ADULTO_MAYOR     2730
INFANTE          2030</code></pre>
<p>Como resultado de este proceso, la variable <code>EDAD</code> queda representada en forma discreta, lo que facilita su integración en el modelo de reglas de asociación. Se observa que la categoría <em>CONFIDENCIAL</em> concentra la mayor proporción de registros, lo cual es consistente con el análisis previo de confidencialidad (~49%).</p>
<p>Este comportamiento sugiere que la ausencia de información en variables relacionadas con la edad no es completamente aleatoria, y podría estar asociada a mecanismos de ocultamiento de información (posible MNAR). A pesar de ello, se mantiene esta categoría con el objetivo de preservar la estructura de los datos y evitar la pérdida de información relevante.</p>
<p>De manera complementaria, la visualización permite contrastar la distribución continua de las edades con su versión discretizada. Se observa una mayor concentración en los grupos de adolescentes y adultos jóvenes, mientras que los extremos (infantes y adultos mayores) presentan menor frecuencia.</p>
<p>Asimismo, se identifican valores atípicos, como edades superiores a 100 años o cercanas a 0, que pueden considerarse outliers. En lugar de eliminarlos, se opta por agruparlos dentro de las categorías existentes, particularmente en <em>ADULTO_MAYOR</em> e <em>INFANTE</em>, respectivamente. Esta decisión introduce un sesgo mínimo, dado que la proporción de estos casos es baja, y permite mantener la integridad del conjunto de datos.</p>
<p>En conjunto, la discretización de la variable <code>EDAD</code> permite reducir la complejidad del espacio de ítems, mejorar la interpretabilidad de los patrones y facilitar la generación de reglas de asociación más relevantes. Todo esto, es posible observarlo como se muestra a continuación.</p>
<div id="cbe19e0e" class="cell" data-execution_count="13">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Configuración de estilo con colores más profesionales</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>sns.set_theme(style<span class="op">=</span><span class="st">"whitegrid"</span>)</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Aumentamos el tamaño de la figura para mejor visibilidad</span></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">22</span>, <span class="dv">10</span>))</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Histograma de Edades (Izquierda) - Rojo oscuro y curva KDE marcada (se mantiene)</span></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>sns.histplot(edades_numericas.dropna(), bins<span class="op">=</span><span class="dv">50</span>, kde<span class="op">=</span><span class="va">True</span>, ax<span class="op">=</span>axes[<span class="dv">0</span>], color<span class="op">=</span><span class="st">'darkred'</span>, </span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>             line_kws<span class="op">=</span>{<span class="st">'linewidth'</span>: <span class="dv">4</span>})</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_title(<span class="st">'Distribución de Edades Original (Antes de Discretizar)'</span>, fontsize<span class="op">=</span><span class="dv">16</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_xlabel(<span class="st">'Edad'</span>, fontsize<span class="op">=</span><span class="dv">13</span>)</span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_ylabel(<span class="st">'Frecuencia'</span>, fontsize<span class="op">=</span><span class="dv">13</span>)</span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Gráfico de Barras (Derecha) - Paleta 'crest' para un acabado más profesional y elegante</span></span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a>orden_categorias <span class="op">=</span> [<span class="st">'INFANTE'</span>, <span class="st">'ADOLESCENTE'</span>, <span class="st">'JOVEN'</span>, <span class="st">'ADULTO'</span>, <span class="st">'ADULTO_MAYOR'</span>, <span class="st">'CONFIDENCIAL'</span>]</span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a>sns.countplot(data<span class="op">=</span>frame, x<span class="op">=</span><span class="st">'EDAD'</span>, order<span class="op">=</span>orden_categorias, ax<span class="op">=</span>axes[<span class="dv">1</span>], palette<span class="op">=</span><span class="st">'crest'</span>, hue<span class="op">=</span><span class="st">'EDAD'</span>, legend<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb18-19"><a href="#cb18-19" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_title(<span class="st">'Distribución por Categorías Discretizadas (Después)'</span>, fontsize<span class="op">=</span><span class="dv">16</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb18-20"><a href="#cb18-20" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_xlabel(<span class="st">'Categoría de Edad'</span>, fontsize<span class="op">=</span><span class="dv">13</span>)</span>
<span id="cb18-21"><a href="#cb18-21" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_ylabel(<span class="st">'Frecuencia'</span>, fontsize<span class="op">=</span><span class="dv">13</span>)</span>
<span id="cb18-22"><a href="#cb18-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-23"><a href="#cb18-23" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb18-24"><a href="#cb18-24" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="heatmaps/DistribucionEDAD.png" class="img-fluid figure-img"></p>
<figcaption>Distribucion continua de las fechas</figcaption>
</figure>
</div>
<p>A continuación, se procede a discretizar las variables <code>ANIO_DESAPARICION</code> y <code>ANIO_REGISTRO</code>. Las variables relacionadas con el mes se preservan sin transformación adicional, con el objetivo de mantener cierta granularidad temporal que permita identificar patrones específicos asociados a periodos mensuales.</p>
<p>Previo a la discretización, se analiza la distribución continua de ambas variables. Se observa que la función de densidad presenta un comportamiento creciente en los años más recientes, particularmente en los últimos cinco años. Asimismo, ambas distribuciones (año de desaparición y año de registro) muestran una forma similar, lo que sugiere una relación estrecha entre ambas variables.</p>
<p>No obstante, se identifican ligeras diferencias en las medidas de tendencia central: mientras que la mediana se mantiene alrededor del año 2020, la media presenta variaciones entre ambas distribuciones. Este comportamiento sugiere la posible existencia de registros donde la fecha de desaparición y la fecha de registro no coinciden temporalmente, lo que puede reflejar retrasos en el proceso de registro.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="heatmaps/fechaContinua.png" class="img-fluid figure-img"></p>
<figcaption>Proporcion continua y discreta de las edades</figcaption>
</figure>
</div>
<p>Para la discretización de los años, se considera el comportamiento observado en la distribución, particularmente el crecimiento en ciertos periodos. En lugar de utilizar intervalos de igual tamaño, se opta por definir <strong>intervalos no equidistantes</strong>, basados en criterios empíricos que reflejan cambios relevantes en la frecuencia de los datos a lo largo del tiempo.</p>
<p>Los intervalos definidos son:<br>
<code>['1962-1999', '2000-2006', '2007-2009', '2010-2015', '2016-2020', '2021-2023', '2024-2025', 'CONFIDENCIAL']</code></p>
<p>Esta discretización permite agrupar los datos en segmentos temporales más representativos, reduciendo la cardinalidad y facilitando la generación de reglas de asociación más interpretables.</p>
<div id="1d5ea168" class="cell" data-execution_count="14">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Definir los bins y etiquetas para los intervalos de años solicitados</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>bins_anios <span class="op">=</span> [<span class="dv">1962</span>, <span class="dv">1999</span>, <span class="dv">2006</span>, <span class="dv">2009</span>, <span class="dv">2015</span>, <span class="dv">2020</span>, <span class="dv">2023</span>, <span class="dv">2025</span>]</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>labels_anios <span class="op">=</span> [<span class="st">'1962-1999'</span>, <span class="st">'2000-2006'</span>, <span class="st">'2007-2009'</span>, <span class="st">'2010-2015'</span>, <span class="st">'2016-2020'</span>, <span class="st">'2021-2023'</span>, <span class="st">'2024-2025'</span>]</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Aplicar la discretización a ANIO_DESAPARICION</span></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>frame[<span class="st">'ANIO_DESAPARICION'</span>] <span class="op">=</span> pd.cut(frame[<span class="st">'ANIO_DESAPARICION'</span>], bins<span class="op">=</span>bins_anios, labels<span class="op">=</span>labels_anios, include_lowest<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>frame[<span class="st">'ANIO_DESAPARICION'</span>] <span class="op">=</span> frame[<span class="st">'ANIO_DESAPARICION'</span>].astype(<span class="bu">object</span>).fillna(<span class="st">'CONFIDENCIAL'</span>)</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Aplicar la discretización a ANIO_REGISTRO</span></span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>frame[<span class="st">'ANIO_REGISTRO'</span>] <span class="op">=</span> pd.cut(frame[<span class="st">'ANIO_REGISTRO'</span>], bins<span class="op">=</span>bins_anios, labels<span class="op">=</span>labels_anios, include_lowest<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>frame[<span class="st">'ANIO_REGISTRO'</span>] <span class="op">=</span> frame[<span class="st">'ANIO_REGISTRO'</span>].astype(<span class="bu">object</span>).fillna(<span class="st">'CONFIDENCIAL'</span>)</span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Definir los bins y etiquetas para los intervalos de años solicitados</span></span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>bins_anios <span class="op">=</span> [<span class="dv">1962</span>, <span class="dv">1999</span>, <span class="dv">2006</span>, <span class="dv">2009</span>, <span class="dv">2015</span>, <span class="dv">2020</span>, <span class="dv">2023</span>, <span class="dv">2025</span>]</span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a>labels_anios <span class="op">=</span> [<span class="st">'1962-1999'</span>, <span class="st">'2000-2006'</span>, <span class="st">'2007-2009'</span>, <span class="st">'2010-2015'</span>, <span class="st">'2016-2020'</span>, <span class="st">'2021-2023'</span>, <span class="st">'2024-2025'</span>]</span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Aplicar la discretización a ANIO_DESAPARICION</span></span>
<span id="cb19-18"><a href="#cb19-18" aria-hidden="true" tabindex="-1"></a>frame[<span class="st">'ANIO_DESAPARICION'</span>] <span class="op">=</span> pd.cut(frame[<span class="st">'ANIO_DESAPARICION'</span>], bins<span class="op">=</span>bins_anios, labels<span class="op">=</span>labels_anios, include_lowest<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb19-19"><a href="#cb19-19" aria-hidden="true" tabindex="-1"></a>frame[<span class="st">'ANIO_DESAPARICION'</span>] <span class="op">=</span> frame[<span class="st">'ANIO_DESAPARICION'</span>].astype(<span class="bu">object</span>).fillna(<span class="st">'CONFIDENCIAL'</span>)</span>
<span id="cb19-20"><a href="#cb19-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-21"><a href="#cb19-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Aplicar la discretización a ANIO_REGISTRO</span></span>
<span id="cb19-22"><a href="#cb19-22" aria-hidden="true" tabindex="-1"></a>frame[<span class="st">'ANIO_REGISTRO'</span>] <span class="op">=</span> pd.cut(frame[<span class="st">'ANIO_REGISTRO'</span>], bins<span class="op">=</span>bins_anios, labels<span class="op">=</span>labels_anios, include_lowest<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb19-23"><a href="#cb19-23" aria-hidden="true" tabindex="-1"></a>frame[<span class="st">'ANIO_REGISTRO'</span>] <span class="op">=</span> frame[<span class="st">'ANIO_REGISTRO'</span>].astype(<span class="bu">object</span>).fillna(<span class="st">'CONFIDENCIAL'</span>)</span>
<span id="cb19-24"><a href="#cb19-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-25"><a href="#cb19-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Mostrar los conteos para verificar la discretización</span></span>
<span id="cb19-26"><a href="#cb19-26" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Distribución ANIO_DESAPARICION:"</span>)</span>
<span id="cb19-27"><a href="#cb19-27" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(frame[<span class="st">'ANIO_DESAPARICION'</span>].value_counts())</span>
<span id="cb19-28"><a href="#cb19-28" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Distribución ANIO_REGISTRO:"</span>)</span>
<span id="cb19-29"><a href="#cb19-29" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(frame[<span class="st">'ANIO_REGISTRO'</span>].value_counts())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Como resultado del proceso de discretización, se obtiene una distribución categórica para ambas variables. Se observa que la categoría <em>CONFIDENCIAL</em> concentra una proporción significativa de los registros, consistente con el análisis previo de confidencialidad.</p>
<p>Por otro lado, los intervalos más recientes (<code>2010-2025</code>) presentan la mayor concentración de registros, lo cual es coherente con el comportamiento creciente observado en la distribución continua. Asimismo, las distribuciones de <code>ANIO_DESAPARICION</code> y <code>ANIO_REGISTRO</code> mantienen una forma similar, lo que refuerza la relación entre ambas variables.</p>
<pre class="output"><code>Distribución ANIO_DESAPARICION:
ANIO_DESAPARICION
CONFIDENCIAL    49151
2024-2025       13672
2016-2020       12013
2010-2015       11267
2021-2023       10825
2007-2009        1361
2000-2006         306
1962-1999         289
Name: count, dtype: int64

Distribución ANIO_REGISTRO:
ANIO_REGISTRO
CONFIDENCIAL    49151
2024-2025       13757
2016-2020       11990
2010-2015       11233
2021-2023       10821
2007-2009        1353
2000-2006         301
1962-1999         278
Name: count, dtype: int64</code></pre>
<p>Al visualizar las distribuciones discretizadas, se observa que las diferencias en medidas como la media se vuelven menos perceptibles debido al proceso de agrupación. Sin embargo, ambas variables conservan una estructura similar en términos de frecuencia por intervalo.</p>
<p>Esto indica que la discretización logra preservar las tendencias generales de los datos, al mismo tiempo que reduce la complejidad del espacio de ítems. Como resultado, se facilita la identificación de patrones temporales relevantes sin incurrir en una alta dimensionalidad.</p>
<div id="43d32dc8" class="cell" data-execution_count="15">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Configuración de estilo</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>sns.set_theme(style<span class="op">=</span><span class="st">"whitegrid"</span>)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">22</span>, <span class="dv">10</span>))</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Definimos el orden cronológico para los ejes</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>orden_anios <span class="op">=</span> [<span class="st">'1962-1999'</span>, <span class="st">'2000-2006'</span>, <span class="st">'2007-2009'</span>, <span class="st">'2010-2015'</span>, <span class="st">'2016-2020'</span>, <span class="st">'2021-2023'</span>, <span class="st">'2024-2025'</span>, <span class="st">'CONFIDENCIAL'</span>]</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Distribución Discretizada: Año de Desaparición</span></span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>sns.countplot(data<span class="op">=</span>frame, x<span class="op">=</span><span class="st">'ANIO_DESAPARICION'</span>, order<span class="op">=</span>orden_anios, ax<span class="op">=</span>axes[<span class="dv">0</span>], palette<span class="op">=</span><span class="st">'crest'</span>, hue<span class="op">=</span><span class="st">'ANIO_DESAPARICION'</span>, legend<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_title(<span class="st">'Distribución por Intervalos: Año de Desaparición'</span>, fontsize<span class="op">=</span><span class="dv">16</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_xlabel(<span class="st">'Intervalo de Año'</span>, fontsize<span class="op">=</span><span class="dv">13</span>)</span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_ylabel(<span class="st">'Frecuencia'</span>, fontsize<span class="op">=</span><span class="dv">13</span>)</span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].tick_params(axis<span class="op">=</span><span class="st">'x'</span>, rotation<span class="op">=</span><span class="dv">45</span>)</span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Distribución Discretizada: Año de Registro</span></span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a>sns.countplot(data<span class="op">=</span>frame, x<span class="op">=</span><span class="st">'ANIO_REGISTRO'</span>, order<span class="op">=</span>orden_anios, ax<span class="op">=</span>axes[<span class="dv">1</span>], palette<span class="op">=</span><span class="st">'crest'</span>, hue<span class="op">=</span><span class="st">'ANIO_REGISTRO'</span>, legend<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb21-17"><a href="#cb21-17" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_title(<span class="st">'Distribución por Intervalos: Año de Registro'</span>, fontsize<span class="op">=</span><span class="dv">16</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb21-18"><a href="#cb21-18" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_xlabel(<span class="st">'Intervalo de Año'</span>, fontsize<span class="op">=</span><span class="dv">13</span>)</span>
<span id="cb21-19"><a href="#cb21-19" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_ylabel(<span class="st">'Frecuencia'</span>, fontsize<span class="op">=</span><span class="dv">13</span>)</span>
<span id="cb21-20"><a href="#cb21-20" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].tick_params(axis<span class="op">=</span><span class="st">'x'</span>, rotation<span class="op">=</span><span class="dv">45</span>)</span>
<span id="cb21-21"><a href="#cb21-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-22"><a href="#cb21-22" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb21-23"><a href="#cb21-23" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="heatmaps/DiscretizadoFECHA.png" class="img-fluid figure-img"></p>
<figcaption>Proporcion discreta de las fechas</figcaption>
</figure>
</div>
</section>
</section>
<section id="construccion-y-evaluacion-del-modelo-de-reglas" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="construccion-y-evaluacion-del-modelo-de-reglas"><span class="header-section-number">3.3</span> Construccion y evaluacion del modelo de reglas</h2>
<div id="0342f1e6" class="cell" data-execution_count="16">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>numero_transacciones <span class="op">=</span> <span class="bu">len</span>(transacciones_codificadas)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>dimensiones <span class="op">=</span> transacciones_codificadas.shape</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>numero_items <span class="op">=</span> transacciones_codificadas.shape[<span class="dv">1</span>]</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>proporcion <span class="op">=</span> transacciones_codificadas.to_numpy().mean()</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'numero de transacciones : </span><span class="sc">{</span>numero_transacciones<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'dimensiones : </span><span class="sc">{</span>dimensiones<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'items distintos : </span><span class="sc">{</span>numero_items<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Presencia de items : </span><span class="sc">{</span><span class="bu">round</span>(proporcion, <span class="dv">6</span>)<span class="sc">}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<pre class="output"><code>numero de transacciones : 98884
dimensiones : (98884, 1649)
items distintos : 1649
Presencia de items : 0.006064</code></pre>
<p>Una vez finalizado el preprocesamiento, se observa una reducción considerable en la dimensionalidad de la matriz binaria, obteniendo 1,649 ítems distintos sobre un total de 98,884 transacciones.</p>
<p>La proporción de presencia de ítems (0.006064) indica que la matriz es altamente dispersa (sparse), es decir, la mayoría de las transacciones contienen un número reducido de ítems en comparación con el total posible. Este comportamiento es característico en problemas de reglas de asociación con variables categóricas de alta cardinalidad.</p>
<p>La baja densidad de la matriz implica un reto en la aplicación del algoritmo Apriori, particularmente en la selección del umbral mínimo de soporte, ya que valores demasiado altos podrían eliminar patrones relevantes, mientras que valores muy bajos incrementarían significativamente el costo computacional y la generación de reglas poco informativas.</p>
<p>No obstante, este comportamiento era esperado debido a la naturaleza del conjunto de datos y a las transformaciones realizadas durante el preprocesamiento, las cuales priorizan la interpretabilidad de los patrones sobre la densidad del espacio de ítems.</p>
<p>Con el objetivo de analizar la estructura de la matriz binaria, se realiza una visualización de un subconjunto de transacciones. En particular, se consideran las <strong>primeras 15 transacciones</strong> y los <strong>50 ítems más frecuentes</strong> dentro de este subconjunto. Para ello, se ordenan los ítems en función de su frecuencia, permitiendo identificar aquellos con mayor presencia relativa.</p>
<p>En la representación gráfica, cada punto indica la presencia de un ítem en una transacción específica, es decir, una posición <em>(i, j)</em> donde el valor es verdadero en la matriz binaria. Este tipo de visualización permite observar de manera directa la dispersión y los patrones de co-ocurrencia entre ítems.</p>
<div id="e42d9a37" class="cell" data-execution_count="17">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> graficar_transacciones_con_nombres(datos: pd.DataFrame, inicio: <span class="bu">int</span> <span class="op">=</span> <span class="dv">0</span>, fin: <span class="bu">int</span> <span class="op">=</span> <span class="dv">50</span>, top_n_items: <span class="bu">int</span> <span class="op">=</span> <span class="dv">30</span>, titulo: <span class="bu">str</span> <span class="op">=</span> <span class="st">""</span>):</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Seleccionamos el rango de transacciones (segmentación)</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>    muestra <span class="op">=</span> datos.iloc[inicio:fin]</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Calculamos frecuencia global para seleccionar los ítems más importantes</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>    frecuencia_total <span class="op">=</span> muestra.<span class="bu">sum</span>(axis<span class="op">=</span><span class="dv">0</span>).sort_values(ascending<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>    top_items <span class="op">=</span> frecuencia_total.head(top_n_items).index</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Filtramos la muestra solo con el top N de ítems</span></span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>    muestra_filtrada <span class="op">=</span> muestra[top_items]</span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Obtenemos coordenadas</span></span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a>    coordenadas_y, coordenadas_x <span class="op">=</span> muestra_filtrada.to_numpy().nonzero()</span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Ajuste de dimensiones</span></span>
<span id="cb24-16"><a href="#cb24-16" aria-hidden="true" tabindex="-1"></a>    ancho <span class="op">=</span> <span class="bu">max</span>(<span class="dv">10</span>, top_n_items <span class="op">*</span> <span class="fl">0.4</span>)</span>
<span id="cb24-17"><a href="#cb24-17" aria-hidden="true" tabindex="-1"></a>    alto <span class="op">=</span> <span class="bu">max</span>(<span class="dv">6</span>, (fin <span class="op">-</span> inicio) <span class="op">*</span> <span class="fl">0.2</span>)</span>
<span id="cb24-18"><a href="#cb24-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-19"><a href="#cb24-19" aria-hidden="true" tabindex="-1"></a>    plt.figure(figsize<span class="op">=</span>(ancho, alto))</span>
<span id="cb24-20"><a href="#cb24-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-21"><a href="#cb24-21" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Color morado oscuro profesional (Deep Purple)</span></span>
<span id="cb24-22"><a href="#cb24-22" aria-hidden="true" tabindex="-1"></a>    plt.scatter(coordenadas_x, coordenadas_y, marker<span class="op">=</span><span class="st">"s"</span>, s<span class="op">=</span><span class="dv">150</span>, color<span class="op">=</span><span class="st">'#301934'</span>, alpha<span class="op">=</span><span class="fl">0.9</span>)</span>
<span id="cb24-23"><a href="#cb24-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-24"><a href="#cb24-24" aria-hidden="true" tabindex="-1"></a>    plt.gca().invert_yaxis()</span>
<span id="cb24-25"><a href="#cb24-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-26"><a href="#cb24-26" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Eje X con los nombres de los ítems</span></span>
<span id="cb24-27"><a href="#cb24-27" aria-hidden="true" tabindex="-1"></a>    plt.xticks(</span>
<span id="cb24-28"><a href="#cb24-28" aria-hidden="true" tabindex="-1"></a>        ticks<span class="op">=</span><span class="bu">range</span>(<span class="bu">len</span>(top_items)),</span>
<span id="cb24-29"><a href="#cb24-29" aria-hidden="true" tabindex="-1"></a>        labels<span class="op">=</span>top_items,</span>
<span id="cb24-30"><a href="#cb24-30" aria-hidden="true" tabindex="-1"></a>        rotation<span class="op">=</span><span class="dv">90</span>,</span>
<span id="cb24-31"><a href="#cb24-31" aria-hidden="true" tabindex="-1"></a>        fontsize<span class="op">=</span><span class="dv">10</span></span>
<span id="cb24-32"><a href="#cb24-32" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb24-33"><a href="#cb24-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-34"><a href="#cb24-34" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Eje Y con los índices de transacciones</span></span>
<span id="cb24-35"><a href="#cb24-35" aria-hidden="true" tabindex="-1"></a>    plt.yticks(</span>
<span id="cb24-36"><a href="#cb24-36" aria-hidden="true" tabindex="-1"></a>        <span class="bu">range</span>(<span class="bu">len</span>(muestra)),</span>
<span id="cb24-37"><a href="#cb24-37" aria-hidden="true" tabindex="-1"></a>        [<span class="ss">f"T</span><span class="sc">{</span>i<span class="op">+</span><span class="dv">1</span><span class="sc">}</span><span class="ss">"</span> <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(inicio, fin)],</span>
<span id="cb24-38"><a href="#cb24-38" aria-hidden="true" tabindex="-1"></a>        fontsize<span class="op">=</span><span class="dv">9</span></span>
<span id="cb24-39"><a href="#cb24-39" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb24-40"><a href="#cb24-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-41"><a href="#cb24-41" aria-hidden="true" tabindex="-1"></a>    plt.xlabel(<span class="ss">f"Top </span><span class="sc">{</span>top_n_items<span class="sc">}</span><span class="ss"> ítems más frecuentes"</span>, fontsize<span class="op">=</span><span class="dv">12</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb24-42"><a href="#cb24-42" aria-hidden="true" tabindex="-1"></a>    plt.ylabel(<span class="st">"Transacciones"</span>, fontsize<span class="op">=</span><span class="dv">12</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb24-43"><a href="#cb24-43" aria-hidden="true" tabindex="-1"></a>    plt.title(titulo <span class="kw">or</span> <span class="ss">f"Matriz de Transacciones(Top </span><span class="sc">{</span>top_n_items<span class="sc">}</span><span class="ss"> Items)"</span>, fontsize<span class="op">=</span><span class="dv">14</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb24-44"><a href="#cb24-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-45"><a href="#cb24-45" aria-hidden="true" tabindex="-1"></a>    plt.grid(<span class="va">True</span>, linestyle<span class="op">=</span><span class="st">':'</span>, alpha<span class="op">=</span><span class="fl">0.5</span>)</span>
<span id="cb24-46"><a href="#cb24-46" aria-hidden="true" tabindex="-1"></a>    plt.tight_layout()</span>
<span id="cb24-47"><a href="#cb24-47" aria-hidden="true" tabindex="-1"></a>    plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>graficar_transacciones_con_nombres( datos=transacciones_codificadas, inicio=0, fin=15, top_n_items=50 )</p>
<p><img src="heatmaps/Top15Dispersa.png" class="img-fluid" alt="Muestra las primeras transacciones de co ocurrencia 1"> <img src="heatmaps/MatrizDispersa.png" class="img-fluid" alt="Proporcion continua y discreta de las edades"></p>
<p>La primera visualización muestra la co-ocurrencia de los ítems más frecuentes en un subconjunto reducido de transacciones:</p>
<p>A partir de esta representación, se observa que ciertos ítems aparecen de forma recurrente en múltiples transacciones, formando patrones verticales que indican alta frecuencia relativa. En contraste, otros ítems presentan una aparición más esporádica, lo que evidencia la heterogeneidad en la distribución de los datos Particularmente se observa que los items relacionados con INFANTE, ESTADO DE MEXICO, HOMBRE, MUJER, DESAPARECIDA son de mayor co ocurrencia en las transacciones</p>
</section>
<section id="refinamiento-y-ajuste" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="refinamiento-y-ajuste"><span class="header-section-number">3.4</span> Refinamiento y ajuste</h2>
<section id="eliminiacion-de-redundancia" class="level3" data-number="3.4.1">
<h3 data-number="3.4.1" class="anchored" data-anchor-id="eliminiacion-de-redundancia"><span class="header-section-number">3.4.1</span> Eliminiacion de redundancia</h3>
</section>
<section id="restricciones-en-reglas" class="level3" data-number="3.4.2">
<h3 data-number="3.4.2" class="anchored" data-anchor-id="restricciones-en-reglas"><span class="header-section-number">3.4.2</span> Restricciones en reglas</h3>
</section>
<section id="reglas-maximas" class="level3" data-number="3.4.3">
<h3 data-number="3.4.3" class="anchored" data-anchor-id="reglas-maximas"><span class="header-section-number">3.4.3</span> Reglas maximas</h3>
</section>
<section id="reglas-en-transacciones" class="level3" data-number="3.4.4">
<h3 data-number="3.4.4" class="anchored" data-anchor-id="reglas-en-transacciones"><span class="header-section-number">3.4.4</span> Reglas en transacciones</h3>
</section>
</section>
<section id="visualizacion-de-reglas" class="level2" data-number="3.5">
<h2 data-number="3.5" class="anchored" data-anchor-id="visualizacion-de-reglas"><span class="header-section-number">3.5</span> Visualizacion de reglas</h2>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>